<HTML>
<HEAD>
<meta charset="UTF-8">
<title>notToThrow - Atrium 0.12.0</title>
<link rel="stylesheet" href="../../style.css">
</HEAD>
<BODY>
<a href="../index.html">doc</a>&nbsp;/&nbsp;<a href="index.html">ch.tutteli.atrium.api.infix.en_GB</a>&nbsp;/&nbsp;<a href="./not-to-throw.html">notToThrow</a><br/>
<br/>
<h1>notToThrow</h1>
<a name="ch.tutteli.atrium.api.infix.en_GB$notToThrow(ch.tutteli.atrium.creating.Expect((ch.tutteli.atrium.api.infix.en_GB.notToThrow.T)))"></a>
<code><span class="keyword">fun </span><span class="symbol">&lt;</span><span class="identifier">R</span><span class="symbol">, </span><span class="identifier">T</span>&nbsp;<span class="symbol">:</span>&nbsp;<span class="symbol">(</span><span class="symbol">)</span>&nbsp;<span class="symbol">-&gt;</span>&nbsp;<a href="not-to-throw.html#R"><span class="identifier">R</span></a><span class="symbol">&gt;</span> <a href="../ch.tutteli.atrium.creating/-expect/index.html"><span class="identifier">Expect</span></a><span class="symbol">&lt;</span><a href="not-to-throw.html#T"><span class="identifier">T</span></a><span class="symbol">&gt;</span><span class="symbol">.</span><span class="identifier">notToThrow</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="../ch.tutteli.atrium.creating/-expect/index.html"><span class="identifier">Expect</span></a><span class="symbol">&lt;</span><a href="not-to-throw.html#R"><span class="identifier">R</span></a><span class="symbol">&gt;</span></code> <a href="https://github.com/robstoll/atrium/tree/v0.12.0/apis/infix-en_GB/atrium-api-infix-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/infix/en_GB/fun0Assertions.kt#L64">(source)</a>
<p>Expects that no <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html">Throwable</a> is thrown at all when calling the subject (a lambda with arity 0, i.e. without arguments)
and changes the subject of the assertion to the return value of type <a href="not-to-throw.html#R">R</a>.</p>
<h3>Exceptions</h3>
<p><a name="AssertionError"></a>
<code>AssertionError</code> - Might throw an <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-assertion-error/index.html">AssertionError</a> if the assertion made is not correct.</p>
<p><strong>Return</strong><br/>
An <a href="../ch.tutteli.atrium.creating/-expect/index.html">Expect</a> with the new type <a href="not-to-throw.html#R">R</a>.</p>
<a name="ch.tutteli.atrium.api.infix.en_GB$notToThrow(ch.tutteli.atrium.creating.Expect((ch.tutteli.atrium.api.infix.en_GB.notToThrow.T)), kotlin.Function1((ch.tutteli.atrium.creating.Expect((ch.tutteli.atrium.api.infix.en_GB.notToThrow.R)), kotlin.Unit)))"></a>
<code><span class="keyword">infix</span> <span class="keyword">fun </span><span class="symbol">&lt;</span><span class="identifier">R</span><span class="symbol">, </span><span class="identifier">T</span>&nbsp;<span class="symbol">:</span>&nbsp;<span class="symbol">(</span><span class="symbol">)</span>&nbsp;<span class="symbol">-&gt;</span>&nbsp;<a href="not-to-throw.html#R"><span class="identifier">R</span></a><span class="symbol">&gt;</span> <a href="../ch.tutteli.atrium.creating/-expect/index.html"><span class="identifier">Expect</span></a><span class="symbol">&lt;</span><a href="not-to-throw.html#T"><span class="identifier">T</span></a><span class="symbol">&gt;</span><span class="symbol">.</span><span class="identifier">notToThrow</span><span class="symbol">(</span><span class="identifier" id="ch.tutteli.atrium.api.infix.en_GB$notToThrow(ch.tutteli.atrium.creating.Expect((ch.tutteli.atrium.api.infix.en_GB.notToThrow.T)), kotlin.Function1((ch.tutteli.atrium.creating.Expect((ch.tutteli.atrium.api.infix.en_GB.notToThrow.R)), kotlin.Unit)))/assertionCreator">assertionCreator</span><span class="symbol">:</span>&nbsp;<a href="../ch.tutteli.atrium.creating/-expect/index.html"><span class="identifier">Expect</span></a><span class="symbol">&lt;</span><a href="not-to-throw.html#R"><span class="identifier">R</span></a><span class="symbol">&gt;</span><span class="symbol">.</span><span class="symbol">(</span><span class="symbol">)</span>&nbsp;<span class="symbol">-&gt;</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html"><span class="identifier">Unit</span></a><span class="symbol">)</span><span class="symbol">: </span><a href="../ch.tutteli.atrium.creating/-expect/index.html"><span class="identifier">Expect</span></a><span class="symbol">&lt;</span><a href="not-to-throw.html#R"><span class="identifier">R</span></a><span class="symbol">&gt;</span></code> <a href="https://github.com/robstoll/atrium/tree/v0.12.0/apis/infix-en_GB/atrium-api-infix-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/infix/en_GB/fun0Assertions.kt#L73">(source)</a>
<p>Expects that no <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html">Throwable</a> is thrown at all when calling the subject (a lambda with arity 0, i.e. without arguments)
and that the corresponding return value holds all assertions the given <a href="not-to-throw.html#ch.tutteli.atrium.api.infix.en_GB$notToThrow(ch.tutteli.atrium.creating.Expect((ch.tutteli.atrium.api.infix.en_GB.notToThrow.T)), kotlin.Function1((ch.tutteli.atrium.creating.Expect((ch.tutteli.atrium.api.infix.en_GB.notToThrow.R)), kotlin.Unit)))/assertionCreator">assertionCreator</a> creates.</p>
<h3>Exceptions</h3>
<p><a name="AssertionError"></a>
<code>AssertionError</code> - Might throw an <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-assertion-error/index.html">AssertionError</a> if the assertion made is not correct.</p>
<p><strong>Return</strong><br/>
An <a href="../ch.tutteli.atrium.creating/-expect/index.html">Expect</a> with the new type <a href="not-to-throw.html#R">R</a>.</p>
</BODY>
</HTML>
