<HTML>
<HEAD>
<meta charset="UTF-8">
<title>notToThrow - Atrium 0.8.0</title>
<link rel="stylesheet" href="../../style.css">
</HEAD>
<BODY>
<a href="../index.html">doc</a>&nbsp;/&nbsp;<a href="index.html">ch.tutteli.atrium.api.cc.en_GB</a>&nbsp;/&nbsp;<a href="./not-to-throw.html">notToThrow</a><br/>
<br/>
<h1>notToThrow</h1>
<a name="ch.tutteli.atrium.api.cc.en_GB$notToThrow(ch.tutteli.atrium.domain.creating.throwable.thrown.ThrowableThrown.Builder)"></a>
<code><span class="keyword">fun </span><a href="../ch.tutteli.atrium.domain.creating.throwable.thrown/-throwable-thrown/-builder/index.html"><span class="identifier">Builder</span></a><span class="symbol">.</span><span class="identifier">notToThrow</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html"><span class="identifier">Unit</span></a></code> <a href="https://github.com/robstoll/atrium/tree/v0.8.0//apis/cc-en_GB/atrium-api-cc-en_GB-common/src/main/kotlin/ch/tutteli/atrium/api/cc/en_GB/throwableAssertions.kt#L32">(source)</a>
<p>Makes the assertion that no <a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html">Throwable</a> is thrown at all.</p>
<h3>Exceptions</h3>
<p><a name="AssertionError"></a>
<code>AssertionError</code> - Might throw an <a href="http://docs.oracle.com/javase/6/docs/api/java/lang/AssertionError.html">AssertionError</a> if the assertion made is not correct.</p>
<p><strong>Return</strong><br/>
Notice, that this assertion function cannot provide a fluent API because we assume nothing happens,
so there is nothing we could make assertions on in addition.</p>
</BODY>
</HTML>
